workflows:
  macos-workflow:
    name: macOS Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      vars:
        TERM: xterm-256color
        SHELL: /bin/bash
        FCI_CLONE_DEPTH: 1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Run Setup Script
        script: ./setup.sh
    artifacts:
      - ./obslib.framework.zip
    publishing:
      slack:
        channel: '#general'
        notify_on_build_start: true    # To receive a notification when a build starts
        notify:
          success: true                # To not receive a notification when a build succeeds
          failure: true                # To not receive a notification when a build fails