# Uncomment the next line to define a global platform for your project
platform :osx, '11.0'

target 'pod-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pod-example
pod 'obslib', :path => '../'
end
