name: "Framework Build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Setup Script
        run: ./setup.sh
        shell: bash
      - name: Archive framework
        uses: actions/upload-artifact@v2
        with:
          path: ./obslib.framework.zip
          name: obslib.framework.zip
